site_title: 青岛海湾化学股份有限公司 - 质量监督检验部
site_description: 质量监督检验部是青岛海湾化学股份有限公司的重要技术支持部门，主要负责公司产品质量控制、原材料检验以及环境监测等工作。
contact_phone: 0532-12345678
contact_address: 青岛市黄岛区董家口工业园区
copyright: © 2023 青岛海湾化学股份有限公司
logo: /images/department.jpg 