backend:
  name: github
  repo: justgoinngdown/goingdown
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  client_id: Ov23licGgGSttbxcK43n
  auth_type: pkce

# 设置媒体文件存储位置
media_folder: "images"
public_folder: "/images"

# 本地化设置
locale: 'zh_Hans'

# 网站基本信息
site_url: https://zj.haiwan.me
display_url: https://zj.haiwan.me
logo_url: /images/department.jpg

# 内容集合配置
collections:
  - name: "equipment"
    label: "仪器设备"
    folder: "_equipment"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "设备名称", name: "title", widget: "string"}
      - {label: "型号", name: "model", widget: "string"}
      - {label: "图片", name: "image", widget: "image", required: false}
      - {label: "描述", name: "description", widget: "markdown"}
      - {label: "购入日期", name: "purchase_date", widget: "datetime"}
      - {label: "状态", name: "status", widget: "select", options: ["正常使用", "维修中", "已报废"]}

  - name: "staff"
    label: "人员信息"
    folder: "_staff"
    create: true
    fields:
      - {label: "姓名", name: "name", widget: "string"}
      - {label: "职位", name: "position", widget: "string"}
      - {label: "照片", name: "photo", widget: "image", required: false}
      - {label: "专业", name: "specialty", widget: "string"}
      - {label: "学历", name: "education", widget: "select", options: ["大专", "本科", "研究生"]}
      - {label: "年龄段", name: "age_group", widget: "select", options: ["0-30岁", "31-40岁", "41-50岁", "51岁以上"]}
      - {label: "性别", name: "gender", widget: "select", options: ["男", "女"]}

  - name: "projects"
    label: "分析检测项目"
    folder: "_projects"
    create: true
    fields:
      - {label: "项目名称", name: "title", widget: "string"}
      - {label: "项目描述", name: "description", widget: "markdown"}
      - {label: "使用设备", name: "equipment", widget: "list"}
      - {label: "检测标准", name: "standard", widget: "string"}
      - {label: "检测周期", name: "cycle", widget: "string"}
      - {label: "负责人", name: "manager", widget: "string"}

  - name: "organization"
    label: "组织架构"
    folder: "_organization"
    create: true
    fields:
      - {label: "部门名称", name: "title", widget: "string"}
      - {label: "部门职责", name: "responsibility", widget: "markdown"}
      - {label: "负责人", name: "manager", widget: "string"}
      - {label: "人员数量", name: "staff_count", widget: "number"}
      - {label: "下属小组", name: "teams", widget: "list", fields: [
          {label: "小组名称", name: "name", widget: "string"},
          {label: "组长", name: "leader", widget: "string"},
          {label: "职责描述", name: "description", widget: "text"}
        ]}

  - name: "news"
    label: "发展历程"
    folder: "_news"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "图片", name: "image", widget: "image"}
      - {label: "内容", name: "content", widget: "markdown"}
      - {label: "重要程度", name: "importance", widget: "select", options: ["普通", "重要", "非常重要"]}

  - name: "settings"
    label: "网站设置"
    files:
      - name: "general"
        label: "基本设置"
        file: "_data/settings.yml"
        fields:
          - {label: "网站标题", name: "site_title", widget: "string"}
          - {label: "网站描述", name: "site_description", widget: "text"}
          - {label: "联系电话", name: "contact_phone", widget: "string"}
          - {label: "联系地址", name: "contact_address", widget: "string"}
          - {label: "版权信息", name: "copyright", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image", required: false}

# 编辑器设置
editor:
  preview: true 