backend:
  name: github
  repo: justgoinngdown/goingdown
  branch: main # 默认分支

media_folder: "images/uploads" # 媒体文件存储位置
public_folder: "/images/uploads" # 公共访问路径

collections:
  - name: "equipment" # 设备管理
    label: "设备"
    folder: "_equipment"
    create: true
    fields:
      - {label: "名称", name: "title", widget: "string"}
      - {label: "分类", name: "category", widget: "select", options: ["分析仪器", "光学仪器", "测量仪器", "其他设备"]}
      - {label: "描述", name: "description", widget: "text"}
      - {label: "图片", name: "image", widget: "image", required: false}
      - {label: "特点", name: "features", widget: "list"}
      
  - name: "staff" # 人员管理
    label: "人员"
    folder: "_staff"
    create: true
    fields:
      - {label: "姓名", name: "name", widget: "string"}
      - {label: "职位", name: "position", widget: "string"}
      - {label: "简介", name: "bio", widget: "text"}
      - {label: "照片", name: "photo", widget: "image", required: false}
      
  - name: "projects" # 项目管理
    label: "检测项目"
    folder: "_projects"
    create: true
    fields:
      - {label: "项目名称", name: "title", widget: "string"}
      - {label: "项目类型", name: "type", widget: "select", options: ["化学分析", "物理测试", "环境监测"]}
      - {label: "项目描述", name: "description", widget: "text"}
      - {label: "检测标准", name: "standard", widget: "string"}
      
  - name: "pages" # 页面内容管理
    label: "页面"
    files:
      - name: "home"
        label: "首页"
        file: "_data/home.yml"
        fields:
          - {label: "部门简介", name: "intro", widget: "text"}
          - {label: "服务亮点", name: "highlights", widget: "list", fields: [
              {label: "标题", name: "title", widget: "string"},
              {label: "描述", name: "description", widget: "text"},
              {label: "图标", name: "icon", widget: "string"}
            ]} 